---
title: \sf MEDS5420 - Molecular Genomics
header-includes:
- \usepackage{color}
- \usepackage{float}
- \DeclareUnicodeCharacter{2212}{-}
date: "Spring 2024"
output:
  bookdown::html_document2:
    toc: true
fontsize: 14pt
geometry: margin=1in
---


Thank you to everyone who took MEDS5420 in 2024. Also, A big thanks to Leighton Core, who shared his Functional Genomics class content with me. Dr. Core developed much of the basic command line utilities text and examples that were reproduced with his permission.


# Lecture 1: Introduction to High Throughput Sequencing Technology Lecture

[Lecture 1 PDF](https://guertinlab.github.io/meds5420/Lecture_1/Lecture_1.pdf) \
[Lecture 1 2025 Recording](http://guertinlab.cam.uchc.edu/meds5420_2025/2025_Lecture_1.mp4) \
[Lecture 1 2024 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_1_2024.mp4)

# Lecture 2: Command Line Basics (directories, head, wc, etc.)

[Lecture 2 HTML](https://guertinlab.github.io/meds5420/Lecture_2/Lecture_2.html) \
[Lecture 2 2025 Recording](http://guertinlab.cam.uchc.edu/meds5420_2025/2025_Lecture_2.mp4) \
[Lecture 2 2024 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_2_2024.mp4)

# Lecture 3: Command Line Basics (pipes, compression, and grep)

[Lecture 3 HTML](https://guertinlab.github.io/meds5420/Lecture_3/Lecture_3.html) \
[Lecture 3 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_3_2024.mp4)


# Lecture 4: Command Line Basics (find, cut, variables, scripting, and permissions)

[Lecture 4 HTML](https://guertinlab.github.io/meds5420/Lecture_4/Lecture_4.html) \
[Lecture 4 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_4_2024.mp4)


# Lecture 5: awk 

[Lecture 5 HTML](https://guertinlab.github.io/meds5420/Lecture_5/Lecture_5.html) \
[Lecture 5 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_5_2024.mp4)

# Lecture 6: Logical operators, loops, and Xanadu (the UCHC computing server)

[Lecture 6 HTML](https://guertinlab.github.io/meds5420/Lecture_6/Lecture_6.html) \
[Lecture 6 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_6_2024.mp4)

# Lecture 7: Batch scripts, interactive sessions, and software installs

[Lecture 7 HTML](https://guertinlab.github.io/meds5420/Lecture_7/Lecture_7.html) \
[Lecture 7 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_7_2024.mp4)

# Lecture 8: Illumina data format, QC, and preprocessing

[Lecture 8 HTML](https://guertinlab.github.io/meds5420/Lecture_8/Lecture_8.html) \
[Lecture 8 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_8_2024.mp4)

# Lecture 9: fastx tools preprocessing

[Lecture 9 HTML](https://guertinlab.github.io/meds5420/Lecture_9/Lecture_9.html) \
[Lecture 9 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_9_2024.mp4)

# Lecture 10: Aligning Illumina data

[Lecture 10 HTML](https://guertinlab.github.io/meds5420/Lecture__10/Lecture_10.html) \
[Lecture 10 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_10_2024.mp4)

# Lecture 11: Transcription Factors Lecture

[Lecture 11 PDF_1](https://guertinlab.github.io/meds5420/Lecture__11/Lecture_11_1.pdf) \
[Lecture 11 PDF_2](https://guertinlab.github.io/meds5420/Lecture__11/Lecture_11_2.pdf) \
[Lecture 11 Recording](http://guertinlab.cam.uchc.edu/meds5420_2023/230222_Lec11_recording.mp4)

# Lecture 12: Post-mapping processing with samtools and bedtools

[Lecture 12 HTML](https://guertinlab.github.io/meds5420/Lecture__12/Lecture_12.html) \
[Lecture 12 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_12_2024.mp4)

# Lecture 13: The UCSC genome browser

[Lecture 13 PDF](https://guertinlab.github.io/meds5420/Lecture__13/Lecture_13.pdf) \
[Lecture 13 HTML](https://guertinlab.github.io/meds5420/Lecture__13/Lecture_13.html) \
[Lecture 13 Recording](http://guertinlab.cam.uchc.edu/meds5420_2023/230301_Lec13_recording.mp4)

# Lecture 14: ChIP-seq peak calling

[Lecture 14 HTML](https://guertinlab.github.io/meds5420/Lecture__14/Lecture_14.html) \
[Lecture 14 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_14_2024.mp4)

# Lecture 15: Analyze ChIP-seq peaks with bedtools and awk

[Lecture 15 HTML](https://guertinlab.github.io/meds5420/Lecture__15/Lecture_15.html) \
[Lecture 15 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_15_2024.mp4)

# Lecture 16: de novo motif analysis

[Lecture 16 HTML](https://guertinlab.github.io/meds5420/Lecture__16/Lecture_16.html) \
[Lecture 16 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_16_2024.mp4)

# Lecture 17: Motif queries to genomes and databases

[Lecture 17 HTML](https://guertinlab.github.io/meds5420/Lecture__17/Lecture_17.html) \
[Lecture 17 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_17_2024.mp4)

# Lecture 18: Introduction to `R`

[Lecture 18 HTML](https://guertinlab.github.io/meds5420/Lecture__18/Lecture_18.html) \
[Lecture 18 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_18_2024.mp4)

# Lecture 19: `R` functions and plotting

[Lecture 19 HTML](https://guertinlab.github.io/meds5420/Lecture__19/Lecture_19.html) \
[Lecture 19 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_19_2024.mp4)

# Lecture 20: RNA-seq lecture

[Lecture 20 PDF](https://guertinlab.github.io/meds5420/Lecture__20/Lecture_20.pdf) \
[Lecture 20 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_20_2024.mp4)


# Lectures 21-23: RNA-seq in the command line

[Lecture 21-23 HTML](https://guertinlab.github.io/meds5420/Lecture__21/Lectures_21_to_23.html) \
[Lecture 21 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_21_2024.mp4)
[Lecture 22 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_22_2024.mp4)
[Lecture 23 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_23_2024.mp4)

# Lectures 24-25: RNA-seq in `R`

[Lecture 24-25 HTML](https://guertinlab.github.io/meds5420/Lecture__24/Lectures_24_to_25.html) \
[Lecture 24 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_24_2024.mp4)
[Lecture 25 Recording](http://guertinlab.cam.uchc.edu/meds5420_2024/Lecture_25_2024.mp4)

# Lectures 26-27: ATAC-seq

[Lecture 26-27 HTML](https://guertinlab.github.io/meds5420/Lecture__26/Lectures_26_to_27.html) \
[Lecture 26 Recording](http://guertinlab.cam.uchc.edu/meds5420_2023/230424_Lec26_recording.mp4)
[Lecture 27 Recording](http://guertinlab.cam.uchc.edu/meds5420_2023/230426_Lec27_recording.mp4)
