name: Render Rmd to HTML
on:
  push:
    paths:
      - '**/*.Rmd'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
      - name: Install R and dependencies
        run: |
          sudo Rscript -e 'install.packages(c("knitr", "BiocManager"), repos="http://cran.rstudio.com/")' 
          sudo Rscript -e 'BiocManager::install("BiocStyle")'
          sudo Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
          echo "HERE"
          sudo Rscript -e "system('pwd')"
          sudo Rscript -e "system('ls')"
      - name: Render Rmd to HTML
        run: |
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD | grep .Rmd$); do
            FILENAME=$(basename $file .Rmd)
            echo $file
            echo $FILENAME
            DIRNAME=$(dirname $file)
            Rscript -e "rmarkdown::render(input = '$file', output_file = '${DIRNAME}/${FILENAME}.html', output_format = BiocStyle::html_document())"
          done
      - name: Commit and push changes
        run: |
          cd $GITHUB_WORKSPACE
          git add $(git diff-tree --no-commit-id --name-only -r HEAD | grep .html$)
          git commit -m "Render Rmd to HTML"
          git push origin HEAD:main
