name: Render Rmd to HTML
on:
  push:
    paths:
      - '**.Rmd'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: r-lib/actions/setup-r@v1
        uses: r-lib/actions/setup-pandoc@v1
        uses: r-lib/actions/setup-tinytex@v1
      - name: Install R and dependencies
        run: |
          sudo Rscript -e 'install.packages(c("knitr", "BiocManager", "BiocStyle"), repos="http://cran.rstudio.com/")' 
          sudo Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
          sudo Rscript -e 'rmarkdown::render("Lecture_21/230405_Lecs21_to_24_RNAseq.Rmd", BiocStyle::html_document())'
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rendered Rmd to HTML
          commit_options: '--no-verify'
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
