name: Render Rmd to HTML
on:
  push:
    paths:
      - '**.Rmd'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install R and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install r-base pandoc pandoc-citeproc
          sudo Rscript -e 'install.packages(c("rmarkdown", "knitr", "BiocManager", "BiocStyle"), lib = "./R_libs")' 
      - name: Render Rmd to HTML
        run: Rscript -e 'rmarkdown::render("Lecture_21/230405_Lecs21_to_24_RNAseq.Rmd", BiocStyle::html_document())'
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rendered Rmd to HTML
          commit_options: '--no-verify'
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
