name: Render Rmd to HTML
on:
  push:
    paths:
      - '**.Rmd'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install R and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install r-base pandoc pandoc-citeproc
          Rscript -e 'install.packages(c("rmarkdown", "knitr"))'
      - name: Render Rmd to HTML
        run: Rscript -e 'rmarkdown::render("yourfile.Rmd")'
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rendered Rmd to HTML
          commit_options: '--no-verify'
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
