name: Render Rmd to HTML
on:
  push:
    paths:
      - '**.Rmd'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
      - name: Install R and dependencies
        run: |
          sudo Rscript -e 'install.packages(c("knitr", "BiocManager"), repos="http://cran.rstudio.com/")' 
          sudo Rscript -e 'BiocManager::install("BiocStyle")'
          sudo Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
          sudo Rscript -e 'rmarkdown::render("${{ github.event.inputs.path }}", BiocStyle::html_document())'
      - name: Commit and push changes
        run: |
          git add ${{ github.event.inputs.path }}
          git commit -m "Re-build ${{ github.event.inputs.path }}" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
