name: Render Rmd to HTML

on:
  push:
    paths:
      - '**.Rmd'

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
      
      - name: Install R and dependencies
        run: |
          sudo Rscript -e 'install.packages(c("knitr", "BiocManager"), repos="http://cran.rstudio.com/")' 
          sudo Rscript -e 'BiocManager::install("BiocStyle")'
          sudo Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
      
      - name: Determine modified Rmd file
        id: find_modified_file
        run: echo ::set-output name=FILE_PATH::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.Rmd')
      
      - name: Render Rmd to HTML
        run: |
          if [[ -n "${{ steps.find_modified_file.outputs.FILE_PATH }}" ]]; then
            sudo Rscript -e "rmarkdown::render(input = '${{ steps.find_modified_file.outputs.FILE_PATH }}', BiocStyle::html_document())"
            git add "${{ steps.find_modified_file.outputs.FILE_PATH }}.html"
          fi
      
      - name: Commit and push changes
        run: |
          git diff --quiet && git diff --staged --quiet || git commit -m "Render Rmd file to HTML" && git push origin HEAD:main
